{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "RiX8WhTKGwyQ",
        "outputId": "ed80e5fa-ee0c-45f8-ca5d-8da281a14bd0"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Starting Apple Services Synthetic Data Pipeline...\n",
            "Pipeline Complete! 4 pristine CSV files generated:\n",
            " - dim_app.csv (5 rows)\n",
            " - dim_campaign.csv (4 rows)\n",
            " - dim_user.csv (1000 rows)\n",
            " - fact_subscriptions.csv (1497 rows)\n"
          ]
        }
      ],
      "source": [
        "import pandas as pd\n",
        "import numpy as np\n",
        "from datetime import datetime, timedelta\n",
        "\n",
        "# Set random seed for reproducibility\n",
        "np.random.seed(42)\n",
        "\n",
        "# Configuration\n",
        "NUM_USERS = 1000\n",
        "START_DATE = datetime(2026, 1, 1)\n",
        "\n",
        "print(\"Starting Apple Services Synthetic Data Pipeline...\")\n",
        "\n",
        "# =============================================================================\n",
        "# 1. GENERATE DIMENSION TABLES\n",
        "# =============================================================================\n",
        "\n",
        "# -- Dim App --\n",
        "dim_app = pd.DataFrame({\n",
        "    'app_id': [101, 102, 103, 104, 105],\n",
        "    'app_name': ['Apple Music', 'Apple TV+', 'iCloud+', 'Apple Arcade', 'Apple Fitness+'],\n",
        "    'monthly_price': [10.99, 9.99, 2.99, 6.99, 9.99],\n",
        "    'trial_duration_days': [90, 7, 30, 30, 30]\n",
        "})\n",
        "\n",
        "# -- Dim Campaign --\n",
        "dim_campaign = pd.DataFrame({\n",
        "    'campaign_id': [201, 202, 203, 204],\n",
        "    'campaign_name': [\n",
        "        'Holiday Bundle Promo',\n",
        "        'iPhone Upgrade Cross-Sell',\n",
        "        'TikTok Influencer Campaign',\n",
        "        'Organic Search'\n",
        "    ],\n",
        "    'channel': ['Email', 'In-App Notification', 'Paid Social', 'Organic']\n",
        "})\n",
        "\n",
        "# -- Dim User --\n",
        "user_ids = [10000 + i for i in range(NUM_USERS)]\n",
        "dim_user = pd.DataFrame({\n",
        "    'user_id': user_ids,\n",
        "    'region': np.random.choice(['US', 'EU', 'APAC', 'LATAM'], size=NUM_USERS, p=[0.50, 0.25, 0.15, 0.10]),\n",
        "    'signup_date': [START_DATE + timedelta(days=int(np.random.randint(0, 60))) for _ in range(NUM_USERS)]\n",
        "})\n",
        "\n",
        "# =============================================================================\n",
        "# 2. GENERATE FACT TABLE (Subscriptions)\n",
        "# =============================================================================\n",
        "fact_records = []\n",
        "\n",
        "app_ids = dim_app['app_id'].values\n",
        "campaign_ids = dim_campaign['campaign_id'].values\n",
        "campaign_probs = [0.20, 0.40, 0.25, 0.15] # Weighting for organic vs paid\n",
        "\n",
        "for _, user in dim_user.iterrows():\n",
        "    # Simulate that a user tries 1 to 3 different apps over time\n",
        "    num_subs = np.random.choice([1, 2, 3], p=[0.6, 0.3, 0.1])\n",
        "    chosen_apps = np.random.choice(app_ids, size=num_subs, replace=False)\n",
        "\n",
        "    for app_id in chosen_apps:\n",
        "        campaign_id = np.random.choice(campaign_ids, p=campaign_probs)\n",
        "\n",
        "        # Trial start date must be on or after user signup date\n",
        "        trial_start = user['signup_date'] + timedelta(days=int(np.random.randint(0, 30)))\n",
        "        trial_end = trial_start + timedelta(days=30)\n",
        "\n",
        "        # Business Logic: Specific campaigns convert better\n",
        "        base_conv_prob = 0.35\n",
        "        if campaign_id == 202: base_conv_prob = 0.55   # High intent (Cross-sell)\n",
        "        elif campaign_id == 203: base_conv_prob = 0.20 # Low intent (TikTok)\n",
        "        elif campaign_id == 204: base_conv_prob = 0.45 # Medium-High (Organic)\n",
        "\n",
        "        converted = np.random.rand() < base_conv_prob\n",
        "\n",
        "        if converted:\n",
        "            status = 'Active' if np.random.rand() < 0.75 else 'Canceled'\n",
        "            # If they converted, they stayed past trial, generating at least some revenue\n",
        "            num_months_paid = np.random.randint(1, 5) if status == 'Canceled' else 5\n",
        "            monthly_price = dim_app[dim_app['app_id'] == app_id]['monthly_price'].values[0]\n",
        "            total_revenue = round(num_months_paid * monthly_price, 2)\n",
        "        else:\n",
        "            status = 'Trial_Expired'\n",
        "            total_revenue = 0.0\n",
        "\n",
        "        fact_records.append({\n",
        "            'user_id': user['user_id'],\n",
        "            'app_id': app_id,\n",
        "            'campaign_id': campaign_id,\n",
        "            'trial_start_date': trial_start.strftime('%Y-%m-%d'),\n",
        "            'trial_end_date': trial_end.strftime('%Y-%m-%d'),\n",
        "            'status': status,\n",
        "            'total_revenue_usd': total_revenue\n",
        "        })\n",
        "\n",
        "fact_subscriptions = pd.DataFrame(fact_records)\n",
        "\n",
        "# =============================================================================\n",
        "# 3. EXPORT ALL TO CSV\n",
        "# =============================================================================\n",
        "dim_app.to_csv('dim_app.csv', index=False)\n",
        "dim_campaign.to_csv('dim_campaign.csv', index=False)\n",
        "dim_user.to_csv('dim_user.csv', index=False)\n",
        "fact_subscriptions.to_csv('fact_subscriptions.csv', index=False)\n",
        "\n",
        "print(\"Pipeline Complete! 4 pristine CSV files generated:\")\n",
        "print(f\" - dim_app.csv ({len(dim_app)} rows)\")\n",
        "print(f\" - dim_campaign.csv ({len(dim_campaign)} rows)\")\n",
        "print(f\" - dim_user.csv ({len(dim_user)} rows)\")\n",
        "print(f\" - fact_subscriptions.csv ({len(fact_subscriptions)} rows)\")"
      ]
    }
  ]
}